services:
  scd_rest_api:
    container_name: scd_rest_api
    build:
      context: ./rest_api
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    networks:
      - rest_api_mongodb_net
    depends_on:
      - scd_mongodb

  scd_mongodb:
    image: mongo
    container_name: scd_mongodb
    environment:
      - MONGO_INITDB_DATABASE=scd_tema2
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    volumes:
      - mongodb_data:/data/db
    networks:
      - rest_api_mongodb_net
      - mongodb_mongo_express_net

  scd_mongodb_util:
    image: mongo-express
    container_name: scd_mongodb_util
    ports:
      - "8081:8081"
    depends_on:
      - scd_mongodb
    environment:
      - ME_CONFIG_MONGODB_SERVER=scd_mongodb
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=example
      - ME_CONFIG_MONGODB_URL=mongodb://root:example@scd_mongodb:27017
    networks:
      - mongodb_mongo_express_net

networks:
  rest_api_mongodb_net:
  mongodb_mongo_express_net:

volumes:
  mongodb_data: {}
